### ISSUE TITLE
Variable Issue

### ISSUE THREAD

**Issue by dlaarschot** [avinor/terraform-azurerm-vpn#1]
Seems there is an issue with the defined variables.  Getting the below when loading the module.

Error downloading modules: Error loading modules: module simple: Error parsing .terraform/modules/7efad07448398e1e539565aec12738b2/avinor-terraform-azurerm-vpn-f215ba4/main.tf: At 21:25: Unknown token: 21:25 IDENT var.location

**Comment by tesharp** [comment]
Our terraform modules are using terraform 0.12 (-rc1) and will therefore not work correctly if run with 0.11. Its a bit different syntax and usually get this error if run on 0.11
